Repository berty/go-ipfs-log, pull requests merged in 2019-12, with the labels that each got.

#27 feat: update to go 1.13
  .circleci/config.yml
  example/example_log_append_test.go
  example/go.mod
  example/go.sum
  go.mod
  go.sum
  identityprovider/identities.go
  identityprovider/identity.go
  identityprovider/interface.go
  identityprovider/orbitdb.go
  keystore/interface.go
  keystore/keystore.go
  test/utils.go
Labels: ✅ Approved

#29 feat: automatic semantic releases
  .github/CODEOWNERS
  .github/workflows/release.yml
  .releaserc.js
Labels: 🔍 Ready for Review

#28 fix: removed potential race conditions
  log.go
Labels: dependent, ✅ Approved
