Repository berty/go-ipfs-log, pull requests merged in 2020-07, with the labels that each got.

#32 feat: update libp2p to 10.0
  example/go.mod
  example/go.sum
  go.mod
  go.sum
Labels: ✅ Approved

#34 chore: update codecov configuration
  .codecov.yml
Labels: chore, 🔍 Ready for Review

#35 chore: refactor unit tests
  go.mod
  test/bench_add_test.go
  test/bench_join_test.go
  test/entry_io_test.go
  test/entry_test.go
  test/log_append_test.go
  test/log_crdt_test.go
  test/log_heads_tails_test.go
  test/log_iterator_test.go
  test/log_join_concurrent_test.go
  test/log_join_test.go
  test/log_load_test.go
  test/log_references_test.go
  test/log_test.go
  test/signed_log_test.go
  test/utils.go
  test/utils_fixtures_test.go
  test/utils_logcreator_test.go
  test/utils_test.go
Labels: chore, 🔍 Ready for Review

#36 chore: switch to github actions
  .circleci/config.yml
  .github/workflows/go.yml
Labels: chore, 🔍 Ready for Review

#33 feat: setup goleak
  .github/workflows/go.yml
  Makefile
  go.mod
  go.sum
  test/goleak_test.go
  test/utils_test.go
Labels: enhancement, 🔍 Ready for Review

#38 chore: update badges
  .github/workflows/release.yml
  README.md
Labels: chore, 🔍 Ready for Review

#39 fix: bump deps
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review

#40 chore: test on mac
  .github/workflows/go.yml
Labels: chore, 🔍 Ready for Review

#41 fix: revert some deps
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review

#42 fix: bump deps
  go.mod
  go.sum
Labels: bug, 🔍 Ready for Review
